language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script:
  - cp hrz/conf.example.py hrz/conf.py
  - nosetests --with-coverage --cover-package=hrz